services:
  
    rizeway_jqueryui_autocompleter.form.type:
        class: Rizeway\FormBundle\Form\Type\JQueryUIAutocompleterType
        tags:
            -  { name: form.type, alias: rizeway_jqueryui_autocompleter }

    rizeway_xoxco_autocompleter.form.type:
        class: Rizeway\FormBundle\Form\Type\XoxcoAutocompleterType
        tags:
            -  { name: form.type, alias: rizeway_xoxco_autocompleter }
            
    rizeway_autocompleter.form.type:
        class: Rizeway\FormBundle\Form\Type\RizewayAutocompleterType
        tags:
            -  { name: form.type, alias: rizeway_autocompleter }

    rizeway_tinymce.form.type:
        class: Rizeway\FormBundle\Form\Type\TinymceType
        tags:
            -  { name: form.type, alias: rizeway_tinymce }
